title: Vallarasu Sambathkumar
author: Vallarasu Sambathkumar
email: vals@live.in
url: https://vallarasu.in
baseurl: ""
description: Personal blog for tech, books, life and other things.

permalink: /:slug.html

favicon: "favicon.ico"

remote_theme: riggraz/no-style-please

highlighter: rouge
markdown: kramdown

theme_config:
  appearance: "auto"
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
